### ISSUE TITLE
Set column metadata

### ISSUE THREAD

**Issue by sananguliyev** [kelsin/mysql-mimic#30]
Firstly, thanks for your effort creating this repo.

I am testing the code and tried to set some custom session with schema, and realized that it's only possible to set `is nullable`, `comment` or `default` data. Not sure what is the best way to implement since it's checking the depth of schema dict, but it would be great if we can implement it. 

Is there any plan regarding that?

**Comment by barakalon** [comment]
Can you show the actual error along with code that can help reproduce this?

**Comment by sananguliyev** [comment]
@barakalon there is no error log. Even debug mode just shows query plan and stuff like that. Example code:

```
import asyncio

from mysql_mimic import MysqlServer, Session
from mysql_mimic.schema import InfoSchema, Column, info_schema_tables


class MySession(Session):
    async def query(self, expression, sql, attrs):
        return [], []

    async def schema(self):
        schema = InfoSchema(info_schema_tables([
            Column(
                name="id",
                type="BIGINT",
                table="t",
                schema="db",
                # catalog="def",
                # is_nullable=False,
            )
        ]))

        return schema

    async def use(self, database: str) -> None:
        print(database)


if __name__ == "__main__":
    server = MysqlServer(session_factory=MySession)
    asyncio.run(server.serve_forever(port=3308))
```

**Comment by barakalon** [comment]
What client are you using?

```
❯ mysql -P 3308 -h 127.0.0.1
Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 1838546944
Server version: 8.0.29 mysql-mimic

Copyright (c) 2000, 2023, Oracle and/or its affiliates.

Oracle is a registered trademark of Oracle Corporation and/or its
affiliates. Other names may be trademarks of their respective
owners.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

mysql> SHOW COLUMNS FROM t;
+-------+--------+------+------+---------+-------+
| Field | Type   | Null | Key  | Default | Extra |
+-------+--------+------+------+---------+-------+
| id    | BIGINT | YES  | NULL | NULL    | NULL  |
+-------+--------+------+------+---------+-------+
1 row in set (0.02 sec)

mysql>
```

**Comment by sananguliyev** [comment]
Beside of that I remember one more thing. JDBC require timestamp precision. E.g. if I connect to mysql-mimic from Trino then it will fail if there is a timestamp column. that's it would be nice to have possibility to set timestamp precision. And maybe some others, too in order to be compatible.

**Comment by sananguliyev** [comment]
> What client are you using?
> 
> ```
> ❯ mysql -P 3308 -h 127.0.0.1
> Welcome to the MySQL monitor.  Commands end with ; or \g.
> Your MySQL connection id is 1838546944
> Server version: 8.0.29 mysql-mimic
> 
> Copyright (c) 2000, 2023, Oracle and/or its affiliates.
> 
> Oracle is a registered trademark of Oracle Corporation and/or its
> affiliates. Other names may be trademarks of their respective
> owners.
> 
> Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.
> 
> mysql> SHOW COLUMNS FROM t;
> +-------+--------+------+------+---------+-------+
> | Field | Type   | Null | Key  | Default | Extra |
> +-------+--------+------+------+---------+-------+
> | id    | BIGINT | YES  | NULL | NULL    | NULL  |
> +-------+--------+------+------+---------+-------+
> 1 row in set (0.02 sec)
> 
> mysql>
> ```

I am using mysql-cli on Mac

**Comment by barakalon** [comment]
Same.

Can you give me instructions to reproduce the error?

**Comment by barakalon** [comment]
i.e. where are you seeing the malformed packet error?

**Comment by sananguliyev** [comment]
The code I shared is simplified version of my implementation. I have executed the code which I shared here and got this error:

```
Task exception was never retrieved
future: <Task finished name='Task-4' coro=<MysqlServer._client_connected_cb() done, defined at /path/to/project/venv/lib/python3.11/site-packages/mysql_mimic/server.py:63> exception=ConnectionResetError(54, 'Connection reset by peer')>
Traceback (most recent call last):
  File "/path/to/project/venv/lib/python3.11/site-packages/mysql_mimic/server.py", line 77, in _client_connected_cb
    return await connection.start()
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/path/to/project/venv/lib/python3.11/site-packages/mysql_mimic/connection.py", line 91, in start
    await self.command_phase()
  File "/path/to/project/venv/lib/python3.11/site-packages/mysql_mimic/connection.py", line 263, in command_phase
    data = await self.stream.read()
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/path/to/project/venv/lib/python3.11/site-packages/mysql_mimic/stream.py", line 23, in read
    header = await self.reader.read(4)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.2_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/streams.py", line 689, in read
    await self._wait_for_data('read')
  File "/opt/homebrew/Cellar/python@3.11/3.11.2_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/streams.py", line 522, in _wait_for_data
    await self._waiter
  File "/opt/homebrew/Cellar/python@3.11/3.11.2_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/selector_events.py", line 995, in _read_ready__data_received
    data = self._sock.recv(self.max_size)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ConnectionResetError: [Errno 54] Connection reset by peer
```

**Comment by barakalon** [comment]
How are you connecting to the server? This would only happen during a connection, not when start up.

**Comment by sananguliyev** [comment]
Ah ok. The difference is I first run `USE db` and then try to show columns or tables. In that case it fails. Could you please try to switch to db and then try again to reproduce it?

**Comment by barakalon** [comment]
Got it. I can reproduce the error.
Not sure what's going wrong. Seems unrelated to the information schema. Looking...

**Comment by barakalon** [comment]
This was tricky.

The issue had to do with the mysql cli using the deprecated COM_FIELD_LIST command after USE db, for which the [spec](https://dev.mysql.com/doc/dev/mysql-server/latest/page_protocol_com_query_response_text_resultset_column_definition.html#sect_protocol_com_query_response_text_resultset_column_definition_41) is incorrect. ColumnDefinition41 also needs the extra "default" fields, even though its not shown.

The fix: https://github.com/kelsin/mysql-mimic/pull/31

**Comment by sananguliyev** [comment]
Perfect. I will review it.
