### ISSUE TITLE
Connection fails from Metabase

### ISSUE THREAD

**Issue by sananguliyev** [kelsin/mysql-mimic#35]
Metabase is open source BI tool. I have used it to connect `mysql-mimic` but for some reason it does not connect. On metabase side the error is `Index 7 out of bounds for length 7`

I debug it and see the 1st parse handshake returns SSLRequest, but the SSL (https://github.com/kelsin/mysql-mimic/blob/main/mysql_mimic/connection.py#L117) is empty because I do not use SSL connection. I do not know how Metabase connects because mysql-cli is working fine. I have checked Metabase with real MySQL and it worked.

**Comment by barakalon** [comment]
Is Metabase trying to connect with SSL?

**Comment by sananguliyev** [comment]
I do not know how it's connecting in the background. I did not check it, but I disable SSL when I connect from UI.

**Comment by sananguliyev** [comment]
```
ERROR:asyncio:Task exception was never retrieved
future: <Task finished name='Task-13' coro=<MysqlServer._client_connected_cb() done, defined at /Users/sananguliyev/Git/suprism/test/venv/lib/python3.11/site-packages/mysql_mimic/server.py:63> exception=AssertionError()>
Traceback (most recent call last):
  File "/path/to/test/venv/lib/python3.11/site-packages/mysql_mimic/server.py", line 77, in _client_connected_cb
    return await connection.start()
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sananguliyev/Git/suprism/test/venv/lib/python3.11/site-packages/mysql_mimic/connection.py", line 84, in start
    await self.connection_phase()
  File "/Users/sananguliyev/Git/suprism/test/venv/lib/python3.11/site-packages/mysql_mimic/connection.py", line 117, in connection_phase
    assert self.ssl is not None
           ^^^^^^^^^^^^^^^^^^^^
AssertionError
```

**Comment by barakalon** [comment]
This means Metabase is trying to upgrade the connection to SSL.

I don't know much about Metabase - are you sure you're disabling SSL? Maybe Metabase is ignoring you?
In any case, mysql-mimic shouldn't be setting the SSL capability flag if ssl is None, so this is likely an issue with Metabase.

You can also enable SSL with mysql-mimic. I've had some issues with that in the past, so your mileage may vary.
